name: dameeg

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install h5io pyriemann
        pip install flake8 pytest pytest-cov
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 dameeg utils *.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 dameeg utils *.py --count --exit-zero --statistics
    - name: Tests
      run: |
        pytest dameeg --cov-report term --cov=dameeg